version: '3.4'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 33061:3306
    environment:
      - MYSQL_DATABASE=rest_api
      - MYSQL_USER=rest_api
      - MYSQL_PASSWORD=rest_api
      - MYSQL_ROOT_PASSWORD=rest_api
    networks:
      - rest-api

  app:
    build:
      context: .
      target: php
    container_name: app
    working_dir: /usr/share/nginx/html
    depends_on:
      - mysql
    volumes:
      - ./:/usr/share/nginx/html
      - ./php.ini:/usr/local/etc/php/php.ini
    ports:
      - 8080:8080
    command: php -S 0.0.0.0:8080 -t public/
    networks:
      - rest-api

volumes:
  mysql:
    external: true

networks:
  rest-api:
    external: true
