version: '3.4'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 33062:3306
    environment:
      - MYSQL_DATABASE=tests
      - MYSQL_USER=tests
      - MYSQL_PASSWORD=tests
      - MYSQL_ROOT_PASSWORD=tests
    networks:
      - tests

  app:
    build:
      context: .
      target: php
    container_name: app
    working_dir: /var/www/app
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/app/
      - ./php.ini:/usr/local/etc/php/php.ini
    ports:
      - 8080:8080
    command: php -S 0.0.0.0:8080
    networks:
      - tests

volumes:
  mysql:
    external: true

networks:
  tests:
    external: true
